// Acupoint atlas data — ported from the standalone 穴道圖典.html

export interface Point {
  id: string;
  name: string;
  py: string;
  meridian: string;
  view: "front" | "back";
  x: number;
  y: number;
  location: string;
  action: string;
  indications: string;
  // Optional note for points whose取穴 or safety differs by sex / pregnancy.
  genderNote?: string;
  // Optional classical designation(s): 井/滎/輸/經/合、原/絡/郄/募穴、
  // 八會穴、八脈交會穴、四總穴… joined by " · " when a point has several.
  special?: string;
}

export interface Formula {
  name: string;
  pattern: string;
  composition: string;
  usage: string;
  notes: string;
}

export interface SymptomGroup {
  id: string;
  name: string;
  category: string;
  description: string;
  formulas: Formula[];
  points: string[];
}

export const MERIDIAN_COLORS: Record<string, string> = {
  督脈: "#B5402E",
  任脈: "#5C7A5C",
  手太陰肺經: "#7E9CC4",
  手陽明大腸經: "#C9A876",
  足陽明胃經: "#A8835C",
  足太陰脾經: "#5C8B7A",
  手少陰心經: "#A85C7A",
  手太陽小腸經: "#B98A6A",
  足太陽膀胱經: "#5C7AA8",
  足少陰腎經: "#6B8E4E",
  手厥陰心包經: "#7A5CA8",
  手少陽三焦經: "#9A7AC9",
  足少陽膽經: "#4FA39A",
  足厥陰肝經: "#7AA85C",
  經外奇穴: "#8A8273",
};

export const SYMPTOM_CATEGORIES: Record<string, string> = {
  外感類: "#B5402E",
  肺系類: "#5C8B7A",
  脾胃類: "#A8835C",
  婦科類: "#A85C7A",
  神志類: "#7A5CA8",
  肝腎類: "#5C7AA8",
};

export const POINTS: Point[] = [
  // ---- FRONT VIEW ----
  { id: "GV20", name: "百會", py: "Bǎihuì", meridian: "督脈", view: "front", x: 200, y: 12, location: "頭頂正中，兩耳尖連線與正中線交點。", action: "升陽舉陷、開竅醒腦、平肝熄風。", indications: "頭痛、眩暈、健忘、中風、脫肛、提神醒腦。" },
  { id: "EX-HN3", name: "印堂", py: "Yìntáng", meridian: "經外奇穴", view: "front", x: 200, y: 42, location: "兩眉頭連線中點。", action: "鎮靜安神、明目通鼻。", indications: "頭痛、眩暈、鼻塞、失眠、小兒驚風。" },
  { id: "GB14", name: "陽白", py: "Yángbái", meridian: "足少陽膽經", view: "front", x: 188, y: 38, location: "眉中直上一寸，瞳孔正上方。", action: "疏風清熱、明目。", indications: "頭痛、眼瞼下垂、目眩、面癱。" },
  { id: "EX-HN5", name: "太陽", py: "Tàiyáng", meridian: "經外奇穴", view: "front", x: 223, y: 50, location: "眉梢與外眼角間，向後約一橫指凹陷處。", action: "清肝明目、止頭痛。", indications: "偏頭痛、目赤腫痛、三叉神經痛。" },
  { id: "BL2", name: "攢竹", py: "Cuánzhú", meridian: "足太陽膀胱經", view: "front", x: 192, y: 40, location: "眉頭凹陷處。", action: "疏風明目、止痛。", indications: "頭痛、眼疲勞、流淚、眼瞼痙攣。" },
  { id: "ST2", name: "四白", py: "Sìbái", meridian: "足陽明胃經", view: "front", x: 190, y: 56, location: "瞳孔直下，眶下孔處。", action: "祛風明目、通經活絡。", indications: "面癱、眼瞼跳動、鼻竇炎、黑眼圈。" },
  { id: "SI18", name: "顴髎", py: "Quánliáo", meridian: "手太陽小腸經", view: "front", x: 215, y: 64, location: "顴骨下緣，外眼角直下凹陷處。", action: "祛風鎮痛、消腫。", indications: "面癱、牙痛、面部痙攣。" },
  { id: "LI20", name: "迎香", py: "Yíngxiāng", meridian: "手陽明大腸經", view: "front", x: 193, y: 68, location: "鼻翼外緣中點旁，鼻唇溝中。", action: "宣通鼻竅、疏散風熱。", indications: "鼻塞、鼻炎、面癱、面部腫痛。" },
  { id: "GV26", name: "人中", py: "Rénzhōng", meridian: "督脈", view: "front", x: 200, y: 73, location: "人中溝上三分之一與下三分之二交點。", action: "開竅醒神、清熱。", indications: "昏迷急救、中風、面腫、牙齦腫痛。" },
  { id: "TE23", name: "絲竹空", py: "Sīzhúkōng", meridian: "手少陽三焦經", view: "front", x: 212, y: 47, location: "眉梢凹陷處。", action: "清頭明目、疏風止痛。", indications: "偏頭痛、眼疾、面癱。" },
  { id: "CV23", name: "廉泉", py: "Liánquán", meridian: "任脈", view: "front", x: 200, y: 92, location: "喉結上方，舌骨上緣凹陷處。", action: "利喉開竅、化痰。", indications: "咽喉腫痛、語言不利、流涎。" },
  { id: "CV22", name: "天突", py: "Tiāntū", meridian: "任脈", view: "front", x: 200, y: 104, location: "胸骨上窩正中。", action: "宣肺平喘、利咽。", indications: "咳嗽、氣喘、咽喉腫痛、聲音嘶啞。" },
  { id: "KI27", name: "俞府", py: "Shùfǔ", meridian: "足少陰腎經", view: "front", x: 188, y: 120, location: "鎖骨下緣，前正中線旁開二寸。", action: "止咳平喘、和胃降逆。", indications: "咳嗽、氣喘、嘔吐、胸痛。" },
  { id: "LU1", name: "中府", py: "Zhōngfǔ", meridian: "手太陰肺經", view: "front", x: 167, y: 140, location: "鎖骨外側下方，第一肋間隙。", action: "宣肺理氣、止咳化痰。", indications: "咳嗽、氣喘、胸痛、肩背痛。", special: "肺之募穴" },
  { id: "LR14", name: "期門", py: "Qīmén", meridian: "足厥陰肝經", view: "front", x: 174, y: 196, location: "乳頭直下，第六肋間隙。", action: "疏肝理氣、健脾和胃。", indications: "胸脅脹痛、嘔吐、情緒鬱結。", special: "肝之募穴" },
  { id: "CV17", name: "膻中", py: "Dànzhōng", meridian: "任脈", view: "front", x: 200, y: 166, location: "兩乳頭連線中點，胸骨正中。", action: "寬胸理氣、止咳化痰。", indications: "咳嗽、氣喘、胸悶、心悸、乳房脹痛。", genderNote: "定位男女有別：「兩乳頭連線中點」以男性為準；女性乳房位置因人而異，宜改以胸骨中線、平第 4 肋間（約第 4、5 肋間）取穴。", special: "心包之募穴 · 八會穴之氣會" },
  { id: "CV12", name: "中脘", py: "Zhōngwǎn", meridian: "任脈", view: "front", x: 200, y: 230, location: "臍上四寸，前正中線上。", action: "健脾和胃、消食導滯。", indications: "胃痛、腹脹、消化不良、嘔吐。", special: "胃之募穴 · 八會穴之腑會" },
  { id: "ST25", name: "天樞", py: "Tiānshū", meridian: "足陽明胃經", view: "front", x: 176, y: 258, location: "臍旁開二寸。", action: "調理腸胃、理氣消滯。", indications: "腹脹、腹瀉、便秘、月經不調。", special: "大腸之募穴" },
  { id: "CV6", name: "氣海", py: "Qìhǎi", meridian: "任脈", view: "front", x: 200, y: 272, location: "臍下一寸半，前正中線上。", action: "補氣益腎、培補元氣。", indications: "腹痛、虛勞、月經不調、遺尿。" },
  { id: "CV4", name: "關元", py: "Guānyuán", meridian: "任脈", view: "front", x: 200, y: 286, location: "臍下三寸，前正中線上。", action: "溫補腎陽、培元固本。", indications: "小腹冷痛、月經不調、遺尿、虛勞。", special: "小腸之募穴" },
  { id: "LI15", name: "肩髃", py: "Jiānyú", meridian: "手陽明大腸經", view: "front", x: 143, y: 130, location: "肩部，三角肌上，肩峰與肱骨大結節間凹陷。", action: "祛風通絡、利關節。", indications: "肩臂痛、肩周炎、上肢不遂。" },
  { id: "LU5", name: "尺澤", py: "Chǐzé", meridian: "手太陰肺經", view: "front", x: 125, y: 243, location: "肘橫紋上，肱二頭肌腱橈側凹陷。", action: "清肺瀉熱、止咳平喘。", indications: "咳嗽、氣喘、咽喉腫痛、肘臂痛。", special: "肺經合穴" },
  { id: "PC3", name: "曲澤", py: "Qūzé", meridian: "手厥陰心包經", view: "front", x: 129, y: 248, location: "肘橫紋中，肱二頭肌腱尺側緣。", action: "清心瀉火、和胃降逆。", indications: "心痛、心悸、嘔吐、肘臂痛。" },
  { id: "HT3", name: "少海", py: "Shàohǎi", meridian: "手少陰心經", view: "front", x: 135, y: 251, location: "肘橫紋尺側端，肱骨內上髁前緣。", action: "寧心安神、通絡止痛。", indications: "心痛、肘臂攣痛、手顫。", special: "心經合穴" },
  { id: "LI11", name: "曲池", py: "Qūchí", meridian: "手陽明大腸經", view: "front", x: 118, y: 239, location: "屈肘，肘橫紋外端凹陷處。", action: "清熱解表、調和氣血。", indications: "發熱、皮膚病、肩肘關節痛、高血壓。", special: "大腸經合穴" },
  { id: "PC6", name: "內關", py: "Nèiguān", meridian: "手厥陰心包經", view: "front", x: 111, y: 272, location: "腕橫紋上二寸，兩筋之間。", action: "寧心安神、和胃降逆、理氣止痛。", indications: "心悸、胸悶、噁心嘔吐、暈車、失眠。", special: "心包經絡穴 · 八脈交會(通陰維脈)" },
  { id: "LU7", name: "列缺", py: "Lièquē", meridian: "手太陰肺經", view: "front", x: 103, y: 285, location: "橈骨莖突上方，腕橫紋上1.5寸。", action: "宣肺解表、通調任脈。", indications: "咳嗽、氣喘、頭痛、頸項僵硬。", special: "肺經絡穴 · 八脈交會(通任脈) · 四總穴(頭項)" },
  { id: "LU9", name: "太淵", py: "Tàiyuān", meridian: "手太陰肺經", view: "front", x: 101, y: 288, location: "腕掌側橫紋橈側，橈動脈搏動處。", action: "補肺益氣、止咳化痰。", indications: "咳嗽、氣喘、無脈症、腕痛。", special: "肺經原穴 · 輸穴 · 八會穴之脈會" },
  { id: "HT7", name: "神門", py: "Shénmén", meridian: "手少陰心經", view: "front", x: 110, y: 291, location: "腕掌側橫紋尺側端凹陷。", action: "寧心安神、清心瀉火。", indications: "失眠、健忘、心悸、焦慮。", special: "心經原穴 · 輸穴" },
  { id: "LI4", name: "合谷", py: "Hégǔ", meridian: "手陽明大腸經", view: "front", x: 97, y: 309, location: "手背第一、二掌骨間，第二掌骨橈側中點。", action: "疏風解表、清熱止痛。", indications: "頭痛、牙痛、感冒發熱、便秘（孕婦慎用）。", genderNote: "孕婦慎用／忌強刺激：與三陰交合用易催產、動胎氣，懷孕期間避免針刺或重按。", special: "大腸經原穴 · 四總穴(面口)" },
  { id: "PC8", name: "勞宮", py: "Láogōng", meridian: "手厥陰心包經", view: "front", x: 101, y: 316, location: "掌心，第二、三掌骨間，握拳中指尖處。", action: "清心瀉熱、開竅醒神。", indications: "口瘡、心煩、中暑、手心多汗。", special: "心包經滎穴" },
  { id: "LU11", name: "少商", py: "Shàoshāng", meridian: "手太陰肺經", view: "front", x: 93, y: 301, location: "拇指橈側指甲角旁0.1寸。", action: "清肺利咽、開竅醒神。", indications: "咽喉腫痛、咳嗽、高熱昏迷。", special: "肺經井穴" },
  { id: "SI3", name: "後溪", py: "Hòuxī", meridian: "手太陽小腸經", view: "front", x: 108, y: 320, location: "手掌尺側，第五掌指關節後方紋頭凹陷。", action: "通督脈、清熱截瘧。", indications: "頸項強痛、落枕、腰背痛、耳聾。", special: "小腸經輸穴 · 八脈交會(通督脈)" },
  { id: "SP10", name: "血海", py: "Xuèhǎi", meridian: "足太陰脾經", view: "front", x: 178, y: 400, location: "大腿內側，髕骨內上緣上二寸。", action: "調經統血、祛風除濕。", indications: "月經不調、痛經、皮膚搔癢、膝痛。" },
  { id: "LR8", name: "曲泉", py: "Qūquán", meridian: "足厥陰肝經", view: "front", x: 178, y: 425, location: "膝內側，膕橫紋內側端。", action: "疏肝理氣、清濕熱。", indications: "月經不調、膝痛、小便不利。" },
  { id: "GB34", name: "陽陵泉", py: "Yánglíngquán", meridian: "足少陽膽經", view: "front", x: 148, y: 448, location: "膝下，腓骨頭前下方凹陷。", action: "疏肝利膽、舒筋活絡。", indications: "膝痛、坐骨神經痛、肝膽疾患、抽筋。", special: "膽經合穴 · 八會穴之筋會 · 膽之下合穴" },
  { id: "ST36", name: "足三里", py: "Zúsānlǐ", meridian: "足陽明胃經", view: "front", x: 160, y: 453, location: "膝下三寸，脛骨前緣外一橫指。", action: "健脾和胃、補中益氣、扶正培元。", indications: "胃痛、消化不良、疲勞、養生保健第一要穴。", special: "胃經合穴 · 四總穴(肚腹) · 胃之下合穴" },
  { id: "SP9", name: "陰陵泉", py: "Yīnlíngquán", meridian: "足太陰脾經", view: "front", x: 169, y: 456, location: "小腿內側，脛骨內側髁後下方凹陷。", action: "健脾利水、消腫。", indications: "水腫、小便不利、膝痛、腹脹。", special: "脾經合穴" },
  { id: "SP6", name: "三陰交", py: "Sānyīnjiāo", meridian: "足太陰脾經", view: "front", x: 160, y: 525, location: "內踝尖上三寸，脛骨內側緣後方。", action: "健脾益血、調補肝腎、安神。", indications: "月經不調、痛經、失眠、下肢水腫（孕婦禁針）。", genderNote: "婦科要穴，但孕婦禁針、禁強刺激：易引發子宮收縮、動胎氣，懷孕期間務必避免。", special: "足三陰經交會穴" },
  { id: "KI3", name: "太溪", py: "Tàixī", meridian: "足少陰腎經", view: "front", x: 161, y: 545, location: "內踝尖與跟腱之間凹陷處。", action: "滋補腎陰、培補元氣。", indications: "腰痛、耳鳴、失眠、足跟痛。", special: "腎經原穴 · 輸穴" },
  { id: "KI6", name: "照海", py: "Zhàohǎi", meridian: "足少陰腎經", view: "front", x: 162, y: 553, location: "內踝尖下方凹陷處。", action: "滋陰清熱、調補沖任。", indications: "咽喉乾痛、失眠、月經不調。", special: "八脈交會(通陰蹺脈)" },
  { id: "GB39", name: "懸鐘", py: "Xuánzhōng", meridian: "足少陽膽經", view: "front", x: 148, y: 535, location: "外踝尖上三寸，腓骨前緣。", action: "疏肝益腎、舒筋活絡。", indications: "頸項強痛、踝關節痛、下肢痿軟。", special: "八會穴之髓會" },
  { id: "SP3", name: "太白", py: "Tàibái", meridian: "足太陰脾經", view: "front", x: 163, y: 572, location: "足內側緣，第一蹠骨關節後下方凹陷。", action: "健脾化濕、理氣和胃。", indications: "腹脹、腹瀉、胃痛、體倦乏力。", special: "脾經原穴 · 輸穴" },
  { id: "ST44", name: "內庭", py: "Nèitíng", meridian: "足陽明胃經", view: "front", x: 149, y: 578, location: "足背第二、三趾間縫紋端。", action: "清胃瀉火、理氣止痛。", indications: "牙痛、咽喉腫痛、胃痛、足背腫痛。", special: "胃經滎穴" },
  { id: "LR3", name: "太衝", py: "Tàichōng", meridian: "足厥陰肝經", view: "front", x: 155, y: 572, location: "足背，第一、二蹠骨結合部前方凹陷。", action: "平肝熄風、疏肝理氣、清熱明目。", indications: "頭痛、眩暈、情緒煩躁、高血壓。", special: "肝經原穴 · 輸穴" },
  { id: "GV24", name: "神庭", py: "Shéntíng", meridian: "督脈", view: "front", x: 200, y: 30, location: "前髮際正中直上0.5寸。", action: "鎮靜安神、清頭明目。", indications: "頭痛、眩暈、失眠、鼻淵、驚悸。" },
  { id: "CV8", name: "神闕", py: "Shénquè", meridian: "任脈", view: "front", x: 200, y: 258, location: "臍窩正中。", action: "溫陽固脫、健運脾胃。", indications: "腹痛、腹瀉、虛脫、水腫（多用灸法，禁針）。" },
  { id: "CV3", name: "中極", py: "Zhōngjí", meridian: "任脈", view: "front", x: 200, y: 297, location: "臍下四寸，前正中線上。", action: "益腎調經、通利膀胱。", indications: "小便不利、遺尿、月經不調、遺精。", special: "膀胱之募穴" },
  { id: "LI10", name: "手三里", py: "Shǒusānlǐ", meridian: "手陽明大腸經", view: "front", x: 112, y: 258, location: "曲池下二寸，陽溪與曲池連線上。", action: "通經活絡、消腫止痛。", indications: "肘臂痠痛、上肢不遂、腹痛、腹瀉。" },
  { id: "LI5", name: "陽溪", py: "Yángxī", meridian: "手陽明大腸經", view: "front", x: 96, y: 300, location: "腕背橈側，拇指上翹時兩肌腱間凹陷（鼻煙窩）。", action: "清熱散風、通利關節。", indications: "頭痛、目赤、牙痛、腕痛。", special: "大腸經經穴" },
  { id: "LU10", name: "魚際", py: "Yújì", meridian: "手太陰肺經", view: "front", x: 96, y: 313, location: "第一掌骨橈側中點，赤白肉際處。", action: "清肺瀉熱、利咽。", indications: "咳嗽、咽喉腫痛、發熱、掌心熱。", special: "肺經滎穴" },
  { id: "PC7", name: "大陵", py: "Dàlíng", meridian: "手厥陰心包經", view: "front", x: 107, y: 286, location: "腕掌側橫紋中央，兩筋之間。", action: "寧心安神、和胃寬胸。", indications: "心痛、心悸、失眠、胃痛、腕關節痛。", special: "心包經原穴 · 輸穴" },
  { id: "ST34", name: "梁丘", py: "Liángqiū", meridian: "足陽明胃經", view: "front", x: 165, y: 428, location: "髕骨外上緣上二寸。", action: "和胃止痛、舒筋活絡。", indications: "急性胃痛、膝關節腫痛、乳癰。", special: "胃經郄穴" },
  { id: "GB31", name: "風市", py: "Fēngshì", meridian: "足少陽膽經", view: "front", x: 151, y: 405, location: "大腿外側中線，直立垂手時中指尖所到處。", action: "祛風除濕、通經活絡。", indications: "下肢痿痺、半身不遂、遍身搔癢。" },
  { id: "ST40", name: "豐隆", py: "Fēnglóng", meridian: "足陽明胃經", view: "front", x: 156, y: 492, location: "外踝尖上八寸，脛骨前緣外二橫指。", action: "和胃氣、化痰濕。", indications: "咳嗽痰多、頭痛、眩暈、下肢腫痛。", special: "胃經絡穴" },
  { id: "ST41", name: "解溪", py: "Jiěxī", meridian: "足陽明胃經", view: "front", x: 155, y: 556, location: "足背踝關節橫紋中央，兩肌腱之間凹陷。", action: "舒筋活絡、清胃化痰。", indications: "踝關節痛、足下垂、頭痛、腹脹。" },
  { id: "SP4", name: "公孫", py: "Gōngsūn", meridian: "足太陰脾經", view: "front", x: 162, y: 580, location: "足內側緣，第一蹠骨基底前下方赤白肉際。", action: "健脾和胃、通調沖脈。", indications: "胃痛、嘔吐、腹脹、腹瀉、心煩。", special: "脾經絡穴 · 八脈交會(通沖脈)" },
  { id: "LR2", name: "行間", py: "Xíngjiān", meridian: "足厥陰肝經", view: "front", x: 153, y: 582, location: "足背第一、二趾間，趾蹼緣後方赤白肉際。", action: "清瀉肝火、熄風寧神。", indications: "頭痛、目赤、脅痛、月經過多、失眠。" },
  { id: "BL1", name: "睛明", py: "Jīngmíng", meridian: "足太陽膀胱經", view: "front", x: 196, y: 50, location: "目內眥角稍上方凹陷處。", action: "明目退翳、祛風清熱。", indications: "目赤腫痛、流淚、近視、夜盲、視物模糊。" },
  { id: "ST1", name: "承泣", py: "Chéngqì", meridian: "足陽明胃經", view: "front", x: 190, y: 53, location: "瞳孔直下，眼球與眶下緣之間。", action: "祛風散邪、明目止淚。", indications: "目赤腫痛、流淚、眼瞼跳動、近視。" },
  { id: "ST4", name: "地倉", py: "Dìcāng", meridian: "足陽明胃經", view: "front", x: 193, y: 77, location: "口角旁開0.4寸，瞳孔直下。", action: "祛風通絡、舒筋活血。", indications: "口角喎斜、流涎、面癱、三叉神經痛。" },
  { id: "ST6", name: "頰車", py: "Jiáchē", meridian: "足陽明胃經", view: "front", x: 183, y: 81, location: "下頜角前上方一橫指，咬牙時咬肌隆起處。", action: "祛風清熱、開關通絡。", indications: "牙痛、面癱、牙關緊閉、腮腫。" },
  { id: "ST7", name: "下關", py: "Xiàguān", meridian: "足陽明胃經", view: "front", x: 211, y: 61, location: "顴弓下緣，下頜骨髁狀突前方凹陷處。", action: "消腫止痛、聰耳通絡。", indications: "牙痛、面癱、顳頜關節痛、耳鳴。" },
  { id: "CV9", name: "水分", py: "Shuǐfēn", meridian: "任脈", view: "front", x: 200, y: 249, location: "臍上一寸，前正中線上。", action: "利水消腫、健脾和胃。", indications: "水腫、腹脹、腹瀉、小便不利。" },
  { id: "SP15", name: "大橫", py: "Dàhéng", meridian: "足太陰脾經", view: "front", x: 162, y: 258, location: "臍旁開四寸。", action: "溫中散寒、調理腸胃。", indications: "腹脹、腹瀉、便秘、繞臍腹痛。" },
  { id: "LR13", name: "章門", py: "Zhāngmén", meridian: "足厥陰肝經", view: "front", x: 156, y: 232, location: "側腹部，第十一肋游離端下際。", action: "疏肝健脾、理氣散結。", indications: "腹脹、脅痛、消化不良、痞塊。", special: "脾之募穴 · 八會穴之臟會" },
  { id: "GB26", name: "帶脈", py: "Dàimài", meridian: "足少陽膽經", view: "front", x: 151, y: 260, location: "第十一肋游離端直下，平臍處。", action: "調經止帶、健脾利濕。", indications: "月經不調、白帶過多、腰脅痛、疝氣。" },
  { id: "LI1", name: "商陽", py: "Shāngyáng", meridian: "手陽明大腸經", view: "front", x: 89, y: 316, location: "食指橈側指甲角旁0.1寸。", action: "清熱解表、開竅醒神。", indications: "咽喉腫痛、牙痛、發熱、昏迷急救。", special: "大腸經井穴" },
  { id: "SI1", name: "少澤", py: "Shàozé", meridian: "手太陽小腸經", view: "front", x: 113, y: 322, location: "小指尺側指甲角旁0.1寸。", action: "清熱通乳、開竅利咽。", indications: "乳少、乳癰、咽喉腫痛、熱病昏迷。", special: "小腸經井穴" },
  { id: "HT9", name: "少衝", py: "Shàochōng", meridian: "手少陰心經", view: "front", x: 116, y: 318, location: "小指橈側指甲角旁0.1寸。", action: "清心開竅、瀉熱醒神。", indications: "心悸、心痛、熱病、昏迷、癲狂。", special: "心經井穴" },
  { id: "PC9", name: "中衝", py: "Zhōngchōng", meridian: "手厥陰心包經", view: "front", x: 96, y: 326, location: "中指末端最高點中央。", action: "開竅醒神、清心瀉熱。", indications: "中風昏迷、中暑、心痛、小兒驚風。", special: "心包經井穴" },
  { id: "TE1", name: "關衝", py: "Guānchōng", meridian: "手少陽三焦經", view: "front", x: 112, y: 328, location: "無名指尺側指甲角旁0.1寸。", action: "清熱開竅、瀉火利咽。", indications: "頭痛、咽喉腫痛、熱病、中暑昏迷。", special: "三焦經井穴" },
  { id: "CV14", name: "巨闕", py: "Jùquè", meridian: "任脈", view: "front", x: 200, y: 205, location: "臍上六寸，前正中線上。", action: "寧心安神、寬胸化痰。", indications: "心痛、心悸、胸悶、嘔吐、癲狂。", special: "心之募穴" },
  { id: "ST42", name: "衝陽", py: "Chōngyáng", meridian: "足陽明胃經", view: "front", x: 155, y: 566, location: "足背最高處，動脈搏動處。", action: "和胃化痰、通絡寧神。", indications: "胃痛、腹脹、足背腫痛、面腫。", special: "胃經原穴" },
  { id: "ST45", name: "厲兌", py: "Lìduì", meridian: "足陽明胃經", view: "front", x: 143, y: 588, location: "第二趾外側趾甲角旁0.1寸。", action: "清胃瀉熱、寧神醒腦。", indications: "牙痛、咽喉腫痛、多夢、熱病、足背痛。", special: "胃經井穴" },
  { id: "SP1", name: "隱白", py: "Yǐnbái", meridian: "足太陰脾經", view: "front", x: 164, y: 586, location: "大趾內側趾甲角旁0.1寸。", action: "健脾統血、寧神定志。", indications: "月經過多、崩漏、腹脹、多夢、驚風。", special: "脾經井穴" },
  { id: "LR1", name: "大敦", py: "Dàdūn", meridian: "足厥陰肝經", view: "front", x: 157, y: 588, location: "大趾外側趾甲角旁0.1寸。", action: "疏肝理氣、調經止血。", indications: "疝氣、遺尿、月經不調、崩漏、癲癇。", special: "肝經井穴" },
  { id: "GB44", name: "足竅陰", py: "Zúqiàoyīn", meridian: "足少陽膽經", view: "front", x: 136, y: 584, location: "第四趾外側趾甲角旁0.1寸。", action: "清肝瀉熱、通竅聰耳。", indications: "偏頭痛、耳鳴耳聾、目赤、脅痛、多夢。", special: "膽經井穴" },
  { id: "GB41", name: "足臨泣", py: "Zúlínqì", meridian: "足少陽膽經", view: "front", x: 147, y: 574, location: "足背第四、五蹠骨結合部前方凹陷。", action: "疏肝熄風、調經止帶。", indications: "偏頭痛、目赤、脅痛、月經不調、足背腫痛。", special: "膽經輸穴 · 八脈交會(通帶脈)" },
  { id: "GB40", name: "丘墟", py: "Qiūxū", meridian: "足少陽膽經", view: "front", x: 147, y: 558, location: "外踝前下方，趾長伸肌腱外側凹陷。", action: "疏肝利膽、舒筋活絡。", indications: "脅痛、踝關節痛、頸項痛、下肢痿痺。", special: "膽經原穴" },
  { id: "KI1", name: "湧泉", py: "Yǒngquán", meridian: "足少陰腎經", view: "front", x: 152, y: 592, location: "足底前1/3凹陷處（蜷足時足心最凹點）。", action: "滋陰降火、開竅醒神、引火歸元。", indications: "頭頂痛、眩暈、失眠、咽喉痛、足心熱、昏厥急救。", special: "腎經井穴" },
  { id: "LU8", name: "經渠", py: "Jīngqú", meridian: "手太陰肺經", view: "front", x: 110, y: 279, location: "腕橫紋上一寸，橈骨莖突與橈動脈之間。", action: "宣肺平喘、利咽止咳。", indications: "咳嗽、氣喘、胸痛、咽喉腫痛、腕痛。", special: "肺經經穴" },
  { id: "LI2", name: "二間", py: "Èrjiān", meridian: "手陽明大腸經", view: "front", x: 92, y: 312, location: "食指本節（第二掌指關節）前橈側凹陷，赤白肉際。", action: "清熱瀉火、利咽消腫。", indications: "牙痛、咽喉腫痛、目昏、鼻衄。", special: "大腸經滎穴" },
  { id: "LI3", name: "三間", py: "Sānjiān", meridian: "手陽明大腸經", view: "front", x: 95, y: 306, location: "食指本節後橈側凹陷處。", action: "清熱止痛、利咽。", indications: "牙痛、咽喉腫痛、目痛、腹脹、手背腫。", special: "大腸經輸穴" },
  { id: "ST43", name: "陷谷", py: "Xiàngǔ", meridian: "足陽明胃經", view: "front", x: 152, y: 572, location: "足背第二、三蹠骨結合部前方凹陷。", action: "和胃行水、理氣止痛。", indications: "面浮身腫、腸鳴腹痛、足背腫痛。", special: "胃經輸穴" },
  { id: "SP2", name: "大都", py: "Dàdū", meridian: "足太陰脾經", view: "front", x: 161, y: 582, location: "大趾本節前內側凹陷，赤白肉際。", action: "健脾和中、清熱化濕。", indications: "腹脹、胃痛、泄瀉、熱病無汗。", special: "脾經滎穴" },
  { id: "SP5", name: "商丘", py: "Shāngqiū", meridian: "足太陰脾經", view: "front", x: 162, y: 560, location: "內踝前下方凹陷處。", action: "健脾化濕、通調腸胃。", indications: "腹脹、泄瀉、便秘、足踝痛、舌本強痛。", special: "脾經經穴" },
  { id: "HT8", name: "少府", py: "Shàofǔ", meridian: "手少陰心經", view: "front", x: 113, y: 315, location: "掌心第四、五掌骨間，握拳時小指尖所指處。", action: "清心瀉火、寧神。", indications: "心悸、胸痛、手心熱、小便不利、陰癢。", special: "心經滎穴" },
  { id: "HT4", name: "靈道", py: "Língdào", meridian: "手少陰心經", view: "front", x: 113, y: 283, location: "腕橫紋上1.5寸，尺側腕屈肌腱橈側緣。", action: "寧心安神、通絡。", indications: "心痛、心悸、暴喑、肘臂攣痛。", special: "心經經穴" },
  { id: "SI2", name: "前谷", py: "Qiángǔ", meridian: "手太陽小腸經", view: "front", x: 119, y: 320, location: "小指本節（第五掌指關節）前尺側凹陷，赤白肉際。", action: "清熱利咽、通乳。", indications: "熱病、乳少、咽喉腫痛、手指麻木。", special: "小腸經滎穴" },
  { id: "KI2", name: "然谷", py: "Rángǔ", meridian: "足少陰腎經", view: "front", x: 163, y: 564, location: "足內側，舟骨粗隆下方凹陷處。", action: "滋陰補腎、清熱利濕。", indications: "月經不調、遺精、消渴、咽喉腫痛、足跗腫。", special: "腎經滎穴" },
  { id: "KI7", name: "復溜", py: "Fùliū", meridian: "足少陰腎經", view: "front", x: 160, y: 528, location: "太溪直上二寸，跟腱前緣。", action: "補腎益陰、利水消腫。", indications: "水腫、盜汗、自汗、泄瀉、腰脊強痛。", special: "腎經經穴" },
  { id: "KI10", name: "陰谷", py: "Yīngǔ", meridian: "足少陰腎經", view: "front", x: 178, y: 428, location: "膕窩內側，半腱肌與半膜肌腱之間。", action: "益腎調經、清利下焦。", indications: "陽痿、小便難、月經不調、膝膕內側痛。", special: "腎經合穴" },
  { id: "PC5", name: "間使", py: "Jiānshǐ", meridian: "手厥陰心包經", view: "front", x: 113, y: 262, location: "腕橫紋上三寸，掌長肌腱與橈側腕屈肌腱之間。", action: "寬胸理氣、寧心安神。", indications: "心痛、心悸、胃痛、嘔吐、瘧疾、癲狂。", special: "心包經經穴" },
  { id: "GB43", name: "俠溪", py: "Xiáxī", meridian: "足少陽膽經", view: "front", x: 142, y: 580, location: "足背第四、五趾間縫紋端，赤白肉際。", action: "清肝瀉火、聰耳明目。", indications: "偏頭痛、耳鳴耳聾、目赤、脅痛、足跗腫。", special: "膽經滎穴" },
  { id: "GB38", name: "陽輔", py: "Yángfǔ", meridian: "足少陽膽經", view: "front", x: 146, y: 525, location: "外踝尖上四寸，腓骨前緣。", action: "清膽瀉火、舒筋活絡。", indications: "偏頭痛、目外眥痛、脅痛、下肢痿痺。", special: "膽經經穴" },
  { id: "LR4", name: "中封", py: "Zhōngfēng", meridian: "足厥陰肝經", view: "front", x: 160, y: 560, location: "內踝前一寸，脛骨前肌腱內側凹陷。", action: "疏肝理氣、清利下焦。", indications: "疝氣、遺精、小便不利、內踝腫痛。", special: "肝經經穴" },
  { id: "CV15", name: "鳩尾", py: "Jiūwěi", meridian: "任脈", view: "front", x: 200, y: 196, location: "臍上七寸，胸劍聯合下一寸。", action: "寧心安神、寬胸化痰。", indications: "心痛、心悸、癲癇、胸悶、嘔逆。", special: "任脈絡穴" },
  { id: "SP21", name: "大包", py: "Dàbāo", meridian: "足太陰脾經", view: "front", x: 150, y: 200, location: "側胸部，腋中線上，第六肋間隙。", action: "統血養經、寬胸理氣。", indications: "胸脅痛、氣喘、全身痠痛、四肢無力。", special: "脾之大絡" },
  { id: "LU6", name: "孔最", py: "Kǒngzuì", meridian: "手太陰肺經", view: "front", x: 114, y: 262, location: "尺澤與太淵連線上，腕橫紋上七寸。", action: "清肺止血、潤肺降氣。", indications: "咳血、咳嗽、氣喘、咽喉腫痛、痔血。", special: "肺經郄穴" },
  { id: "LI7", name: "溫溜", py: "Wēnliū", meridian: "手陽明大腸經", view: "front", x: 105, y: 275, location: "陽溪與曲池連線上，腕橫紋上五寸。", action: "清熱解毒、調理腸胃。", indications: "頭痛、面腫、咽喉腫痛、腸鳴腹痛、肩背痠痛。", special: "大腸經郄穴" },
  { id: "LI6", name: "偏歷", py: "Piānlì", meridian: "手陽明大腸經", view: "front", x: 103, y: 284, location: "陽溪與曲池連線上，腕橫紋上三寸。", action: "清熱利尿、通經活絡。", indications: "目赤、耳鳴、鼻衄、咽喉腫痛、水腫、手臂痠痛。", special: "大腸經絡穴" },
  { id: "HT6", name: "陰郄", py: "Yīnxì", meridian: "手少陰心經", view: "front", x: 112, y: 287, location: "腕橫紋上0.5寸，尺側腕屈肌腱橈側。", action: "寧心安神、清虛熱。", indications: "心痛、心悸、骨蒸盜汗、吐血、暴喑。", special: "心經郄穴" },
  { id: "HT5", name: "通里", py: "Tōnglǐ", meridian: "手少陰心經", view: "front", x: 113, y: 284, location: "腕橫紋上一寸，尺側腕屈肌腱橈側。", action: "寧心安神、通利舌竅。", indications: "心悸、怔忡、暴喑、舌強不語、腕臂痛。", special: "心經絡穴" },
  { id: "PC4", name: "郄門", py: "Xìmén", meridian: "手厥陰心包經", view: "front", x: 114, y: 253, location: "腕橫紋上五寸，掌長肌腱與橈側腕屈肌腱之間。", action: "寧心安神、清營止血。", indications: "心痛、心悸、心煩、咳血、嘔血、疔瘡。", special: "心包經郄穴" },
  { id: "SP8", name: "地機", py: "Dìjī", meridian: "足太陰脾經", view: "front", x: 168, y: 480, location: "陰陵泉下三寸，脛骨內側緣後方。", action: "健脾滲濕、調經止帶。", indications: "痛經、月經不調、腹痛腹瀉、水腫、小便不利。", special: "脾經郄穴" },
  { id: "KI9", name: "築賓", py: "Zhùbīn", meridian: "足少陰腎經", view: "front", x: 163, y: 505, location: "太溪上五寸，腓腸肌內側肌腹下方。", action: "調補肝腎、清熱寧神。", indications: "癲狂、嘔吐涎沫、疝氣、小腿內側痛。", special: "陰維脈郄穴" },
  { id: "LR6", name: "中都", py: "Zhōngdū", meridian: "足厥陰肝經", view: "front", x: 163, y: 508, location: "內踝尖上七寸，脛骨內側面中央。", action: "疏肝理氣、調經止血。", indications: "脅痛、腹痛、崩漏、惡露不盡、疝氣。", special: "肝經郄穴" },
  { id: "LR5", name: "蠡溝", py: "Lígōu", meridian: "足厥陰肝經", view: "front", x: 162, y: 516, location: "內踝尖上五寸，脛骨內側面中央。", action: "疏肝理氣、調經利濕。", indications: "月經不調、帶下、小便不利、疝氣、外陰瘙癢。", special: "肝經絡穴" },
  { id: "KI8", name: "交信", py: "Jiāoxìn", meridian: "足少陰腎經", view: "front", x: 160, y: 531, location: "太溪上二寸，復溜前方，脛骨內側緣後方。", action: "調經止血、利水通淋。", indications: "月經不調、崩漏、泄瀉、便秘、睪丸腫痛。", special: "陰蹺脈郄穴" },
  { id: "KI4", name: "大鐘", py: "Dàzhōng", meridian: "足少陰腎經", view: "front", x: 161, y: 548, location: "太溪下方稍後，跟腱內側緣前方凹陷。", action: "益腎調氣、強腰利水。", indications: "咳血、氣喘、腰脊強痛、小便不利、癡呆。", special: "腎經絡穴" },
  { id: "KI5", name: "水泉", py: "Shuǐquán", meridian: "足少陰腎經", view: "front", x: 162, y: 551, location: "太溪直下一寸，跟骨結節內側凹陷。", action: "清熱益腎、通經活血。", indications: "月經不調、痛經、小便不利、目昏花。", special: "腎經郄穴" },
  { id: "GB36", name: "外丘", py: "Wàiqiū", meridian: "足少陽膽經", view: "front", x: 144, y: 508, location: "外踝尖上七寸，腓骨前緣。", action: "疏肝理氣、舒筋活絡。", indications: "頸項痛、胸脅痛、下肢痿痺、癲狂。", special: "膽經郄穴" },
  { id: "GB35", name: "陽交", py: "Yángjiāo", meridian: "足少陽膽經", view: "front", x: 144, y: 510, location: "外踝尖上七寸，腓骨後緣。", action: "舒肝理氣、寧神定志。", indications: "胸脅脹滿、下肢痿痺、癲狂、面腫。", special: "陽維脈郄穴" },
  { id: "GB37", name: "光明", py: "Guāngmíng", meridian: "足少陽膽經", view: "front", x: 145, y: 518, location: "外踝尖上五寸，腓骨前緣。", action: "疏肝明目、舒筋活絡。", indications: "目痛、夜盲、視物模糊、乳脹、下肢痿痺。", special: "膽經絡穴" },
  { id: "ST37", name: "上巨虛", py: "Shàngjùxū", meridian: "足陽明胃經", view: "front", x: 156, y: 478, location: "足三里下三寸，脛骨前緣外一橫指。", action: "調和腸胃、通腑化滯。", indications: "腹痛、腹瀉、便秘、闌尾炎、下肢痿痺。", special: "大腸之下合穴" },
  { id: "ST39", name: "下巨虛", py: "Xiàjùxū", meridian: "足陽明胃經", view: "front", x: 155, y: 500, location: "上巨虛下三寸，脛骨前緣外一橫指。", action: "調理腸胃、通經活絡。", indications: "小腹痛、泄瀉、乳癰、下肢痿痺。", special: "小腸之下合穴" },
  { id: "GV23", name: "上星", py: "Shàngxīng", meridian: "督脈", view: "front", x: 200, y: 24, location: "前髮際正中直上一寸。", action: "清頭明目、通利鼻竅。", indications: "頭痛、目痛、鼻塞、鼻衄、熱病。" },
  { id: "EX-HN1", name: "四神聰", py: "Sìshéncōng", meridian: "經外奇穴", view: "front", x: 200, y: 19, location: "百會前後左右各一寸，共四穴。", action: "鎮靜安神、醒腦開竅。", indications: "頭痛、眩暈、失眠、健忘、癲癇。" },
  { id: "ST8", name: "頭維", py: "Tóuwéi", meridian: "足陽明胃經", view: "front", x: 174, y: 26, location: "額角髮際直上0.5寸。", action: "祛風止痛、清頭明目。", indications: "偏頭痛、目眩、目痛、迎風流淚。" },
  { id: "GB8", name: "率谷", py: "Shuàigǔ", meridian: "足少陽膽經", view: "front", x: 228, y: 40, location: "耳尖直上，入髮際1.5寸。", action: "平肝熄風、通絡止痛。", indications: "偏頭痛、眩暈、耳鳴、小兒驚風。" },
  { id: "TE20", name: "角孫", py: "Jiǎosūn", meridian: "手少陽三焦經", view: "front", x: 231, y: 47, location: "耳尖正對髮際處。", action: "清熱消腫、散風止痛。", indications: "耳部腫痛、目赤腫痛、牙痛、頰腫。" },
  { id: "TE21", name: "耳門", py: "Ěrmén", meridian: "手少陽三焦經", view: "front", x: 231, y: 60, location: "耳屏上切跡前，下頜骨髁突後緣凹陷。", action: "開竅聰耳、瀉熱活絡。", indications: "耳鳴耳聾、聤耳、牙痛。" },
  { id: "SI19", name: "聽宮", py: "Tīnggōng", meridian: "手太陽小腸經", view: "front", x: 229, y: 65, location: "耳屏前，下頜骨髁狀突後緣，張口呈凹陷處。", action: "聰耳開竅、寧神。", indications: "耳鳴耳聾、聤耳、牙痛、癲狂。" },
  { id: "GB2", name: "聽會", py: "Tīnghuì", meridian: "足少陽膽經", view: "front", x: 219, y: 70, location: "耳屏間切跡前，下頜骨髁突後緣，張口呈凹陷處。", action: "開竅聰耳、活絡安神。", indications: "耳鳴耳聾、牙痛、面癱、下頜脫臼。" },
  { id: "TE17", name: "翳風", py: "Yìfēng", meridian: "手少陽三焦經", view: "front", x: 218, y: 77, location: "耳垂後方，乳突與下頜角之間凹陷處。", action: "聰耳通竅、祛風止痛。", indications: "耳鳴耳聾、面癱、牙關緊閉、腮腺炎、頰腫。" },
  { id: "CV24", name: "承漿", py: "Chéngjiāng", meridian: "任脈", view: "front", x: 200, y: 82, location: "頦唇溝正中凹陷處。", action: "祛風通絡、鎮靜開竅。", indications: "口喎、流涎、牙齦腫痛、面腫、暴喑。" },
  { id: "CV13", name: "上脘", py: "Shàngwǎn", meridian: "任脈", view: "front", x: 200, y: 221, location: "臍上五寸，前正中線上。", action: "和胃降逆、化痰寧神。", indications: "胃痛、嘔吐、呃逆、腹脹、癲癇。" },
  { id: "CV10", name: "下脘", py: "Xiàwǎn", meridian: "任脈", view: "front", x: 200, y: 243, location: "臍上二寸，前正中線上。", action: "健脾和胃、消積化滯。", indications: "胃痛、腹脹、嘔吐、食穀不化、泄瀉。" },
  { id: "CV2", name: "曲骨", py: "Qūgǔ", meridian: "任脈", view: "front", x: 200, y: 303, location: "恥骨聯合上緣，前正中線上。", action: "溫腎助陽、調經止帶。", indications: "小便不利、遺尿、遺精、陽痿、月經不調、帶下。" },
  { id: "ST21", name: "梁門", py: "Liángmén", meridian: "足陽明胃經", view: "front", x: 178, y: 230, location: "臍上四寸，前正中線旁開二寸。", action: "和胃理氣、消積化滯。", indications: "胃痛、嘔吐、食慾不振、腹脹、泄瀉。" },
  { id: "ST28", name: "水道", py: "Shuǐdào", meridian: "足陽明胃經", view: "front", x: 180, y: 286, location: "臍下三寸，前正中線旁開二寸。", action: "利水消腫、調經止痛。", indications: "小腹脹痛、小便不利、水腫、痛經、不孕。" },
  { id: "ST29", name: "歸來", py: "Guīlái", meridian: "足陽明胃經", view: "front", x: 180, y: 295, location: "臍下四寸，前正中線旁開二寸。", action: "活血調經、溫經散寒。", indications: "月經不調、痛經、閉經、疝氣、陰挺。" },
  { id: "KI16", name: "肓俞", py: "Huāngshù", meridian: "足少陰腎經", view: "front", x: 192, y: 258, location: "臍中旁開0.5寸。", action: "理氣止痛、潤腸通便。", indications: "腹痛、腹脹、嘔吐、便秘、泄瀉。" },
  { id: "KI12", name: "大赫", py: "Dàhè", meridian: "足少陰腎經", view: "front", x: 192, y: 293, location: "臍下四寸，前正中線旁開0.5寸。", action: "益腎助陽、調經固精。", indications: "遺精、陽痿、月經不調、帶下、陰挺。" },
  { id: "GB13", name: "本神", py: "Běnshén", meridian: "足少陽膽經", view: "front", x: 210, y: 28, location: "前髮際上0.5寸，神庭旁開3寸。", action: "祛風定驚、安神。", indications: "頭痛、眩暈、癲癇、小兒驚風、失眠。" },
  { id: "GB4", name: "頷厭", py: "Hànyàn", meridian: "足少陽膽經", view: "front", x: 216, y: 36, location: "頭維與曲鬢弧形連線的上1/4處。", action: "疏風清熱、通絡止痛。", indications: "偏頭痛、目眩、耳鳴、齒痛。" },
  { id: "GB5", name: "懸顱", py: "Xuánlú", meridian: "足少陽膽經", view: "front", x: 222, y: 44, location: "頭維與曲鬢弧形連線的中點。", action: "疏風清熱、通絡。", indications: "偏頭痛、面腫、目赤腫痛、齒痛。" },
  { id: "GB6", name: "懸釐", py: "Xuánlí", meridian: "足少陽膽經", view: "front", x: 226, y: 52, location: "頭維與曲鬢弧形連線的下1/4處。", action: "疏風清熱、通絡止痛。", indications: "偏頭痛、面腫、目外眥痛、耳鳴。" },
  { id: "GB7", name: "曲鬢", py: "Qūbìn", meridian: "足少陽膽經", view: "front", x: 226, y: 60, location: "耳前鬢角髮際後緣，與耳尖水平處。", action: "祛風止痛、開竅。", indications: "頭痛連齒、頰頷腫、牙關緊閉。" },
  { id: "GB10", name: "浮白", py: "Fúbái", meridian: "足少陽膽經", view: "front", x: 229, y: 54, location: "耳後乳突後上方，當天衝與完骨弧線中1/3處。", action: "祛風散熱、理氣散結。", indications: "頭痛、耳鳴耳聾、頸項強痛、癭瘤。" },
  { id: "GB1", name: "瞳子髎", py: "Tóngzǐliáo", meridian: "足少陽膽經", view: "front", x: 218, y: 52, location: "目外眥外側0.5寸，眶骨外緣凹陷。", action: "疏散風熱、明目退翳。", indications: "目赤腫痛、迎風流淚、目翳、偏頭痛。" },
  { id: "GB3", name: "上關", py: "Shàngguān", meridian: "足少陽膽經", view: "front", x: 212, y: 56, location: "顴弓上緣中央，下關直上凹陷處。", action: "聰耳鎮痙、通絡止痛。", indications: "耳鳴耳聾、牙痛、面癱、偏頭痛。" },
  { id: "LI14", name: "臂臑", py: "Bìnào", meridian: "手陽明大腸經", view: "front", x: 132, y: 165, location: "曲池與肩髃連線上，三角肌前下緣。", action: "通經活絡、清熱明目。", indications: "肩臂痛、頸項拘急、目疾、瘰癧。" },
  { id: "ST19", name: "不容", py: "Bùróng", meridian: "足陽明胃經", view: "front", x: 180, y: 205, location: "臍上六寸，前正中線旁開二寸。", action: "和胃降逆、理氣止痛。", indications: "嘔吐、胃痛、食慾不振、腹脹。" },
  { id: "ST22", name: "關門", py: "Guānmén", meridian: "足陽明胃經", view: "front", x: 179, y: 243, location: "臍上三寸，前正中線旁開二寸。", action: "調理腸胃、利水消腫。", indications: "腹脹、腹痛、腸鳴泄瀉、水腫。" },
  { id: "ST23", name: "太乙", py: "Tàiyǐ", meridian: "足陽明胃經", view: "front", x: 180, y: 249, location: "臍上二寸，前正中線旁開二寸。", action: "和胃化痰、寧神。", indications: "胃痛、消化不良、心煩、癲狂。" },
  { id: "ST27", name: "大巨", py: "Dàjù", meridian: "足陽明胃經", view: "front", x: 180, y: 277, location: "臍下二寸，前正中線旁開二寸。", action: "調理腸胃、固腎益精。", indications: "小腹脹滿、小便不利、遺精、早泄。" },
  { id: "KI11", name: "橫骨", py: "Hénggǔ", meridian: "足少陰腎經", view: "front", x: 193, y: 303, location: "臍下五寸，恥骨聯合上緣旁開0.5寸。", action: "益腎助陽、調理下焦。", indications: "小腹脹痛、小便不利、遺精、陽痿、疝氣。" },
  { id: "ST32", name: "伏兔", py: "Fútù", meridian: "足陽明胃經", view: "front", x: 165, y: 400, location: "髕底外上緣上六寸，髂前上棘與髕底外緣連線上。", action: "祛風除濕、舒筋活絡。", indications: "腰膝冷痛、下肢痿痺、腳氣。" },
  { id: "ST33", name: "陰市", py: "Yīnshì", meridian: "足陽明胃經", view: "front", x: 165, y: 420, location: "髕底外上緣上三寸。", action: "溫經散寒、舒筋活絡。", indications: "腿膝冷痛、屈伸不利、下肢痿痺。" },
  { id: "ST35", name: "犢鼻", py: "Dúbí", meridian: "足陽明胃經", view: "front", x: 165, y: 440, location: "髕骨下緣，髕韌帶外側凹陷（外膝眼）。", action: "通經活絡、消腫止痛。", indications: "膝關節痛、屈伸不利、腳氣。" },
  { id: "SP11", name: "箕門", py: "Jīmén", meridian: "足太陰脾經", view: "front", x: 180, y: 375, location: "血海與沖門連線上，血海上六寸。", action: "健脾滲濕、通利下焦。", indications: "小便不利、遺尿、腹股溝腫痛、下肢內側痛。" },
  { id: "GB16", name: "目窗", py: "Mùchuāng", meridian: "足少陽膽經", view: "front", x: 190, y: 20, location: "前髮際上1.5寸，瞳孔直上（頭臨泣後1寸）。", action: "明目開竅、祛風定驚。", indications: "頭痛、目赤腫痛、目眩、鼻塞。" },
  { id: "GB15", name: "頭臨泣", py: "Tóulínqì", meridian: "足少陽膽經", view: "front", x: 188, y: 26, location: "前髮際上0.5寸，瞳孔直上。", action: "聰耳明目、安神。", indications: "頭痛、目眩、目赤、鼻塞、小兒驚癇。" },
  { id: "GB9", name: "天衝", py: "Tiānchōng", meridian: "足少陽膽經", view: "front", x: 234, y: 40, location: "耳根後緣直上，入髮際2寸（率谷後0.5寸）。", action: "祛風定驚、清熱消腫。", indications: "頭痛、齒齦腫痛、癲癇、驚恐。" },
  { id: "GB11", name: "頭竅陰", py: "Tóuqiàoyīn", meridian: "足少陽膽經", view: "front", x: 226, y: 62, location: "耳後乳突後上方，浮白與完骨之間。", action: "祛風清熱、通竅聰耳。", indications: "頭痛、耳鳴耳聾、頸項強痛。" },
  { id: "ST5", name: "大迎", py: "Dàyíng", meridian: "足陽明胃經", view: "front", x: 188, y: 82, location: "下頜角前下方，咬肌附著部前緣，面動脈搏動處。", action: "祛風通絡、消腫止痛。", indications: "面癱、牙關緊閉、頰腫、牙痛。" },
  { id: "ST9", name: "人迎", py: "Rényíng", meridian: "足陽明胃經", view: "front", x: 188, y: 98, location: "喉結旁開1.5寸，胸鎖乳突肌前緣，頸總動脈搏動處。", action: "理氣降逆、利咽散結。", indications: "咽喉腫痛、氣喘、瘰癧、高血壓、頭痛。" },
  { id: "ST10", name: "水突", py: "Shuǐtū", meridian: "足陽明胃經", view: "front", x: 188, y: 108, location: "人迎與氣舍連線中點，胸鎖乳突肌前緣。", action: "宣肺利咽、降逆平喘。", indications: "咽喉腫痛、咳嗽、氣喘、瘰癧。" },
  { id: "ST12", name: "缺盆", py: "Quēpén", meridian: "足陽明胃經", view: "front", x: 176, y: 116, location: "鎖骨上窩中點，前正中線旁開4寸。", action: "寬胸利膈、止咳平喘。", indications: "咳嗽、氣喘、咽喉腫痛、缺盆中痛、瘰癧。" },
  { id: "ST17", name: "乳中", py: "Rǔzhōng", meridian: "足陽明胃經", view: "front", x: 172, y: 168, location: "乳頭中央。", action: "（定位標誌穴）。", indications: "本穴一般不針不灸，僅作胸腹部取穴的定位標誌。", genderNote: "以乳頭中央定位；女性乳房位置因人而異，僅作體表標誌，不作治療刺激。" },
  { id: "ST18", name: "乳根", py: "Rǔgēn", meridian: "足陽明胃經", view: "front", x: 172, y: 180, location: "乳頭直下，第五肋間隙。", action: "通乳化瘀、宣肺止咳。", indications: "乳少、乳癰、乳房脹痛、咳嗽、胸悶。", genderNote: "「乳頭直下第5肋間」以男性為準；女性宜以鎖骨中線與第5肋間定位。" },
  { id: "GB24", name: "日月", py: "Rìyuè", meridian: "足少陽膽經", view: "front", x: 172, y: 206, location: "乳頭直下，第七肋間隙（期門下一肋）。", action: "疏肝利膽、降逆和胃。", indications: "脅肋脹痛、黃疸、嘔吐、吞酸、呃逆。", special: "膽之募穴" },
  { id: "GB25", name: "京門", py: "Jīngmén", meridian: "足少陽膽經", view: "front", x: 152, y: 222, location: "側腰部，第十二肋游離端下際。", action: "益腎利水、健脾溫陽。", indications: "腰痛、脅痛、腹脹、泄瀉、小便不利。", special: "腎之募穴" },
  { id: "GB28", name: "維道", py: "Wéidào", meridian: "足少陽膽經", view: "front", x: 213, y: 292, location: "髂前上棘前下方0.5寸。", action: "調理沖任、利水止痛。", indications: "腰胯痛、少腹痛、帶下、陰挺、疝氣。" },
  { id: "GB29", name: "居髎", py: "Jūliáo", meridian: "足少陽膽經", view: "front", x: 238, y: 305, location: "髂前上棘與股骨大轉子最高點連線中點。", action: "舒筋活絡、益腎強腰。", indications: "腰腿痺痛、癱瘓、疝氣、少腹痛。" },
  { id: "KI26", name: "彧中", py: "Yùzhōng", meridian: "足少陰腎經", view: "front", x: 185, y: 140, location: "第一肋間隙，前正中線旁開2寸。", action: "寬胸理氣、止咳化痰。", indications: "咳嗽、氣喘、胸脅脹滿、不嗜食。" },
  { id: "KI25", name: "神藏", py: "Shéncáng", meridian: "足少陰腎經", view: "front", x: 184, y: 150, location: "第二肋間隙，前正中線旁開2寸。", action: "寬胸理氣、降逆平喘。", indications: "咳嗽、氣喘、胸痛、煩滿、嘔吐。" },
  { id: "KI22", name: "步廊", py: "Bùláng", meridian: "足少陰腎經", view: "front", x: 184, y: 178, location: "第五肋間隙，前正中線旁開2寸。", action: "寬胸理氣、止咳平喘。", indications: "咳嗽、氣喘、胸脅脹痛、嘔吐、不嗜食。" },
  { id: "KI15", name: "中注", py: "Zhōngzhù", meridian: "足少陰腎經", view: "front", x: 192, y: 266, location: "臍下一寸，前正中線旁開0.5寸。", action: "調理下焦、通便調經。", indications: "腹痛、便秘、泄瀉、月經不調。" },
  { id: "KI13", name: "氣穴", py: "Qìxué", meridian: "足少陰腎經", view: "front", x: 192, y: 286, location: "臍下三寸，前正中線旁開0.5寸。", action: "益腎調經、利水止瀉。", indications: "月經不調、帶下、小便不利、泄瀉、腰痛。" },
  { id: "SP12", name: "沖門", py: "Chōngmén", meridian: "足太陰脾經", view: "front", x: 165, y: 300, location: "腹股溝外側，恥骨聯合上緣旁開3.5寸，股動脈外側。", action: "健脾化濕、理氣解痙。", indications: "腹痛、疝氣、帶下、小便不利、崩漏。" },
  { id: "CV21", name: "璇璣", py: "Xuánjī", meridian: "任脈", view: "front", x: 200, y: 116, location: "天突下一寸，前正中線上。", action: "寬胸利肺、止咳化痰。", indications: "咳嗽、氣喘、胸痛、咽喉腫痛。" },
  { id: "CV20", name: "華蓋", py: "Huágài", meridian: "任脈", view: "front", x: 200, y: 128, location: "前正中線上，平第一肋間隙。", action: "寬胸利肺、止咳平喘。", indications: "咳嗽、氣喘、胸脅脹痛、咽喉腫痛。" },
  { id: "CV19", name: "紫宮", py: "Zǐgōng", meridian: "任脈", view: "front", x: 200, y: 140, location: "前正中線上，平第二肋間隙。", action: "寬胸理氣、止咳。", indications: "咳嗽、氣喘、胸痛、咽喉腫痛。" },
  { id: "CV18", name: "玉堂", py: "Yùtáng", meridian: "任脈", view: "front", x: 200, y: 152, location: "前正中線上，平第三肋間隙。", action: "寬胸止咳、降逆。", indications: "咳嗽、氣喘、胸痛、嘔吐、乳房脹痛。" },
  { id: "CV16", name: "中庭", py: "Zhōngtíng", meridian: "任脈", view: "front", x: 200, y: 178, location: "前正中線上，胸劍結合部中點。", action: "寬胸消脹、降逆止嘔。", indications: "胸悶、心痛、嘔吐、小兒吐乳、噎膈。" },
  { id: "ST13", name: "氣戶", py: "Qìhù", meridian: "足陽明胃經", view: "front", x: 170, y: 126, location: "鎖骨下緣，前正中線旁開4寸。", action: "理氣寬胸、止咳平喘。", indications: "咳嗽、氣喘、胸脅脹痛、呃逆。" },
  { id: "ST15", name: "屋翳", py: "Wūyì", meridian: "足陽明胃經", view: "front", x: 170, y: 150, location: "第二肋間隙，前正中線旁開4寸。", action: "止咳化痰、消癰通乳。", indications: "咳嗽、氣喘、胸脅脹痛、乳癰、乳房脹痛。" },
  { id: "ST16", name: "膺窗", py: "Yīngchuāng", meridian: "足陽明胃經", view: "front", x: 171, y: 160, location: "第三肋間隙，前正中線旁開4寸。", action: "止咳寧嗽、消腫清熱。", indications: "咳嗽、氣喘、胸脅脹痛、乳癰。" },
  { id: "ST24", name: "滑肉門", py: "Huáròumén", meridian: "足陽明胃經", view: "front", x: 180, y: 253, location: "臍上一寸，前正中線旁開二寸。", action: "和胃止嘔、寧神。", indications: "胃痛、嘔吐、癲狂、舌強。" },
  { id: "HT1", name: "極泉", py: "Jíquán", meridian: "手少陰心經", view: "front", x: 150, y: 152, location: "腋窩正中，腋動脈搏動處。", action: "寬胸理氣、通經活絡。", indications: "心痛、心悸、脅肋疼痛、肩臂痛、瘰癧。" },
  { id: "HT2", name: "青靈", py: "Qīnglíng", meridian: "手少陰心經", view: "front", x: 138, y: 235, location: "少海上三寸，肱二頭肌內側溝中。", action: "理氣止痛、寬胸寧心。", indications: "心痛、脅痛、肩臂疼痛、頭痛。" },
  { id: "LU3", name: "天府", py: "Tiānfǔ", meridian: "手太陰肺經", view: "front", x: 150, y: 180, location: "腋前紋頭下三寸，肱二頭肌橈側緣。", action: "宣肺理氣、清熱涼血。", indications: "咳嗽、氣喘、鼻衄、上臂內側痛。" },
  { id: "LU4", name: "俠白", py: "Xiábái", meridian: "手太陰肺經", view: "front", x: 146, y: 200, location: "天府下一寸，肘橫紋上五寸，肱二頭肌橈側緣。", action: "宣肺止咳、寬胸理氣。", indications: "咳嗽、氣喘、心痛、煩滿、上臂內側痛。" },
  { id: "LR9", name: "陰包", py: "Yīnbāo", meridian: "足厥陰肝經", view: "front", x: 180, y: 415, location: "髕底上四寸，股內肌與縫匠肌之間。", action: "調經止痛、利尿。", indications: "月經不調、小便不利、遺尿、腰骶引小腹痛。" },
  { id: "LR10", name: "足五里", py: "Zúwǔlǐ", meridian: "足厥陰肝經", view: "front", x: 170, y: 338, location: "氣衝下三寸，大腿內側，動脈搏動處。", action: "清利下焦、疏肝理氣。", indications: "少腹脹痛、小便不利、陰挺、睪丸腫痛。" },
  { id: "LR7", name: "膝關", py: "Xīguān", meridian: "足厥陰肝經", view: "front", x: 167, y: 460, location: "脛骨內側髁後下方，陰陵泉後一寸。", action: "祛風除濕、舒筋活絡。", indications: "膝臏腫痛、下肢痿痺、咽喉痛。" },
  { id: "SP7", name: "漏谷", py: "Lòugǔ", meridian: "足太陰脾經", view: "front", x: 163, y: 505, location: "內踝尖上六寸，脛骨內側緣後方。", action: "健脾滲濕、利尿。", indications: "腹脹腸鳴、小便不利、下肢痿痺。" },

  // ---- BACK VIEW ----
  { id: "GV16", name: "風府", py: "Fēngfǔ", meridian: "督脈", view: "back", x: 200, y: 115, location: "後髮際正中直上一寸，枕骨下凹陷。", action: "祛風散邪、開竅醒腦。", indications: "頭痛、項強、感冒、中風失語。" },
  { id: "GB20", name: "風池", py: "Fēngchí", meridian: "足少陽膽經", view: "back", x: 187, y: 110, location: "後頸部，枕骨下，胸鎖乳突肌與斜方肌間凹陷。", action: "祛風解表、清頭明目。", indications: "頭痛、眩暈、感冒、頸項僵硬、失眠。" },
  { id: "GV14", name: "大椎", py: "Dàzhuī", meridian: "督脈", view: "back", x: 200, y: 128, location: "第七頸椎與第一胸椎棘突間凹陷。", action: "解表通陽、清熱截瘧。", indications: "感冒、發熱、咳嗽、頸背強痛。" },
  { id: "GB21", name: "肩井", py: "Jiānjǐng", meridian: "足少陽膽經", view: "back", x: 170, y: 122, location: "肩上，大椎與肩峰連線中點。", action: "祛風清熱、活絡消腫。", indications: "肩頸痠痛、落枕、上肢不遂（孕婦禁針）。" },
  { id: "SI11", name: "天宗", py: "Tiānzōng", meridian: "手太陽小腸經", view: "back", x: 166, y: 186, location: "肩胛骨中央，肩胛岡下窩中點。", action: "舒筋活絡、理氣消腫。", indications: "肩背痠痛、肩周炎、乳房脹痛。" },
  { id: "BL13", name: "肺俞", py: "Fèishù", meridian: "足太陽膀胱經", view: "back", x: 185, y: 172, location: "第三胸椎棘突下，旁開1.5寸。", action: "宣肺理氣、止咳平喘。", indications: "咳嗽、氣喘、感冒、背痛。", special: "肺之背俞穴" },
  { id: "BL23", name: "腎俞", py: "Shènshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 258, location: "第二腰椎棘突下，旁開1.5寸。", action: "益腎助陽、強腰利水。", indications: "腰痛、耳鳴、遺尿、月經不調。", special: "腎之背俞穴" },
  { id: "GV4", name: "命門", py: "Mìngmén", meridian: "督脈", view: "back", x: 200, y: 260, location: "第二腰椎棘突下，後正中線上。", action: "溫腎壯陽、強腰固本。", indications: "腰痛、遺尿、虛寒體質、月經不調。" },
  { id: "GB30", name: "環跳", py: "Huántiào", meridian: "足少陽膽經", view: "back", x: 236, y: 318, location: "側臀部，股骨大轉子最高點與骶管裂孔連線外1/3處。", action: "祛風除濕、舒筋活絡。", indications: "坐骨神經痛、腰腿痛、下肢痿痺。" },
  { id: "TE5", name: "外關", py: "Wàiguān", meridian: "手少陽三焦經", view: "back", x: 286, y: 272, location: "前臂背側，腕橫紋上二寸，尺橈骨之間。", action: "祛風解表、通經活絡。", indications: "感冒、頭痛、耳鳴、上肢痠痛。", special: "三焦經絡穴 · 八脈交會(通陽維脈)" },
  { id: "BL40", name: "委中", py: "Wěizhōng", meridian: "足太陽膀胱經", view: "back", x: 170, y: 408, location: "膕橫紋中點。", action: "舒筋活絡、清熱涼血。", indications: "腰背痛、膝關節痛、下肢痿軟。", special: "膀胱經合穴 · 四總穴(腰背) · 膀胱之下合穴" },
  { id: "BL60", name: "崑崙", py: "Kūnlún", meridian: "足太陽膀胱經", view: "back", x: 170, y: 540, location: "外踝尖與跟腱之間凹陷處。", action: "舒筋活絡、清熱消腫。", indications: "頭痛、腰背痛、足跟痛、踝關節腫痛。" },
  { id: "BL67", name: "至陰", py: "Zhìyīn", meridian: "足太陽膀胱經", view: "back", x: 160, y: 580, location: "足小趾外側，趾甲角旁0.1寸。", action: "通經活絡、矯正胎位。", indications: "頭痛、目痛、胎位不正。", special: "膀胱經井穴" },
  { id: "BL17", name: "膈俞", py: "Géshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 200, location: "第七胸椎棘突下，旁開1.5寸。", action: "理血和血、寬胸利膈。", indications: "貧血、嘔吐、呃逆、咳血、皮膚搔癢。", special: "八會穴之血會" },
  { id: "BL20", name: "脾俞", py: "Píshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 228, location: "第十一胸椎棘突下，旁開1.5寸。", action: "健脾和胃、利濕升清。", indications: "腹脹、腹瀉、消化不良、水腫、倦怠。", special: "脾之背俞穴" },
  { id: "BL25", name: "大腸俞", py: "Dàchángshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 276, location: "第四腰椎棘突下，旁開1.5寸。", action: "理氣降逆、調和腸胃。", indications: "腹脹、腹瀉、便秘、腰痛。", special: "大腸之背俞穴" },
  { id: "GV3", name: "腰陽關", py: "Yāoyángguān", meridian: "督脈", view: "back", x: 200, y: 276, location: "第四腰椎棘突下凹陷，後正中線上。", action: "溫腎壯陽、舒筋活絡。", indications: "腰骶痛、下肢痿痺、月經不調、遺精。" },
  { id: "BL57", name: "承山", py: "Chéngshān", meridian: "足太陽膀胱經", view: "back", x: 166, y: 470, location: "小腿後正中，腓腸肌兩肌腹之間凹陷的尖角處。", action: "舒筋活絡、理腸療痔。", indications: "小腿抽筋、腰背痛、痔瘡、便秘。" },
  { id: "GV12", name: "身柱", py: "Shēnzhù", meridian: "督脈", view: "back", x: 200, y: 172, location: "第三胸椎棘突下凹陷，後正中線上。", action: "宣肺清熱、寧神鎮咳。", indications: "咳嗽、氣喘、脊背強痛、小兒體弱。" },
  { id: "GV9", name: "至陽", py: "Zhìyáng", meridian: "督脈", view: "back", x: 200, y: 200, location: "第七胸椎棘突下凹陷，後正中線上。", action: "利膽退黃、寬胸利膈。", indications: "黃疸、胸脅脹痛、咳嗽、脊背強痛。" },
  { id: "BL11", name: "大杼", py: "Dàzhù", meridian: "足太陽膀胱經", view: "back", x: 185, y: 160, location: "第一胸椎棘突下，旁開1.5寸。", action: "強筋壯骨、祛風解表。", indications: "頸項強痛、肩背痛、咳嗽、發熱。", special: "八會穴之骨會" },
  { id: "BL15", name: "心俞", py: "Xīnshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 186, location: "第五胸椎棘突下，旁開1.5寸。", action: "寧心安神、寬胸理氣。", indications: "心悸、失眠、健忘、咳嗽、盜汗。", special: "心之背俞穴" },
  { id: "BL18", name: "肝俞", py: "Gānshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 212, location: "第九胸椎棘突下，旁開1.5寸。", action: "疏肝利膽、養血明目。", indications: "脅痛、目疾、眩暈、情緒鬱悶、月經不調。", special: "肝之背俞穴" },
  { id: "BL19", name: "膽俞", py: "Dǎnshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 221, location: "第十胸椎棘突下，旁開1.5寸。", action: "疏肝利膽、清熱化濕。", indications: "黃疸、口苦、脅痛、胃脘脹痛。", special: "膽之背俞穴" },
  { id: "BL21", name: "胃俞", py: "Wèishù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 242, location: "第十二胸椎棘突下，旁開1.5寸。", action: "和胃健脾、消食化滯。", indications: "胃痛、腹脹、嘔吐、消化不良。", special: "胃之背俞穴" },
  { id: "BL32", name: "次髎", py: "Cìliáo", meridian: "足太陽膀胱經", view: "back", x: 190, y: 300, location: "第二骶後孔中，約當髂後上棘與後正中線之間。", action: "補益下焦、調經止帶。", indications: "月經不調、痛經、帶下、腰骶痛、小便不利。" },
  { id: "BL36", name: "承扶", py: "Chéngfú", meridian: "足太陽膀胱經", view: "back", x: 172, y: 332, location: "臀橫紋中點。", action: "舒筋活絡、通便消痔。", indications: "腰骶臀股痛、坐骨神經痛、痔疾。" },
  { id: "BL37", name: "殷門", py: "Yīnmén", meridian: "足太陽膀胱經", view: "back", x: 171, y: 372, location: "承扶下六寸，大腿後正中。", action: "舒筋通絡、強腰健膝。", indications: "腰背痛、下肢痿痺、坐骨神經痛。" },
  { id: "BL62", name: "申脈", py: "Shēnmài", meridian: "足太陽膀胱經", view: "back", x: 174, y: 550, location: "外踝直下方凹陷處。", action: "舒筋活絡、寧心安神。", indications: "頭痛、眩暈、失眠、癲癇、踝關節痛。", special: "八脈交會(通陽蹺脈)" },
  { id: "BL66", name: "足通谷", py: "Zútōnggǔ", meridian: "足太陽膀胱經", view: "back", x: 162, y: 576, location: "足小趾本節前外側凹陷，赤白肉際。", action: "清熱安神、舒筋活絡。", indications: "頭痛、項強、目眩、鼻衄、癲狂。", special: "膀胱經滎穴" },
  { id: "BL65", name: "束骨", py: "Shùgǔ", meridian: "足太陽膀胱經", view: "back", x: 165, y: 568, location: "足小趾本節後外側凹陷，赤白肉際。", action: "清熱散風、寧心通絡。", indications: "頭痛、項強、腰腿痛、癲狂。", special: "膀胱經輸穴" },
  { id: "SI5", name: "陽谷", py: "Yánggǔ", meridian: "手太陽小腸經", view: "back", x: 295, y: 292, location: "腕背尺側，尺骨莖突與三角骨之間凹陷。", action: "清熱明目、舒筋。", indications: "頸頷腫痛、耳鳴耳聾、腕痛、熱病。", special: "小腸經經穴" },
  { id: "SI8", name: "小海", py: "Xiǎohǎi", meridian: "手太陽小腸經", view: "back", x: 287, y: 238, location: "肘內側，尺骨鷹嘴與肱骨內上髁之間凹陷。", action: "清熱通絡、安神定志。", indications: "肘臂疼痛麻木、頭痛、癲癇。", special: "小腸經合穴" },
  { id: "TE2", name: "液門", py: "Yèmén", meridian: "手少陽三焦經", view: "back", x: 300, y: 318, location: "手背第四、五指縫間，指蹼緣後方赤白肉際。", action: "清熱瀉火、聰耳利咽。", indications: "頭痛、目赤、耳鳴耳聾、咽喉腫痛、手臂痛。", special: "三焦經滎穴" },
  { id: "TE3", name: "中渚", py: "Zhōngzhǔ", meridian: "手少陽三焦經", view: "back", x: 300, y: 308, location: "手背第四、五掌骨間，掌指關節後方凹陷。", action: "清熱通絡、開竅益聰。", indications: "頭痛、耳鳴耳聾、目赤、肩背痛、手指不能屈伸。", special: "三焦經輸穴" },
  { id: "TE6", name: "支溝", py: "Zhīgōu", meridian: "手少陽三焦經", view: "back", x: 288, y: 258, location: "腕背橫紋上三寸，尺骨與橈骨之間。", action: "清三焦熱、通腑降逆。", indications: "便秘、脅肋痛、耳鳴耳聾、熱病、落枕。", special: "三焦經經穴" },
  { id: "TE10", name: "天井", py: "Tiānjǐng", meridian: "手少陽三焦經", view: "back", x: 287, y: 233, location: "肘尖（尺骨鷹嘴）上一寸凹陷處。", action: "行氣散結、清熱通絡。", indications: "偏頭痛、肘臂痛、瘰癧、癲癇。", special: "三焦經合穴" },
  { id: "GV1", name: "長強", py: "Chángqiáng", meridian: "督脈", view: "back", x: 200, y: 318, location: "尾骨端下方，尾骨端與肛門連線中點。", action: "寧神鎮痙、通便消痔。", indications: "痔瘡、便血、脫肛、便秘、癲癇、腰脊痛。", special: "督脈絡穴" },
  { id: "SI6", name: "養老", py: "Yǎnglǎo", meridian: "手太陽小腸經", view: "back", x: 296, y: 286, location: "腕背尺側，尺骨小頭橈側骨縫凹陷。", action: "清頭明目、舒筋活絡。", indications: "目視不明、肩背肘臂痠痛、急性腰痛。", special: "小腸經郄穴" },
  { id: "SI7", name: "支正", py: "Zhīzhèng", meridian: "手太陽小腸經", view: "back", x: 293, y: 268, location: "腕背橫紋上五寸，尺骨尺側緣。", action: "清熱解表、安神定志。", indications: "頭痛、項強、肘臂痠痛、熱病、癲狂。", special: "小腸經絡穴" },
  { id: "TE7", name: "會宗", py: "Huìzōng", meridian: "手少陽三焦經", view: "back", x: 293, y: 256, location: "腕背橫紋上三寸，支溝尺側，尺骨橈側緣。", action: "清熱聰耳、舒筋通絡。", indications: "耳聾耳鳴、上肢痠痛、癲癇。", special: "三焦經郄穴" },
  { id: "BL58", name: "飛揚", py: "Fēiyáng", meridian: "足太陽膀胱經", view: "back", x: 172, y: 498, location: "崑崙直上七寸，腓腸肌外下緣與跟腱之間。", action: "祛風清熱、舒筋活絡。", indications: "頭痛、目眩、鼻塞鼻衄、腰腿痛、痔疾。", special: "膀胱經絡穴" },
  { id: "BL59", name: "跗陽", py: "Fùyáng", meridian: "足太陽膀胱經", view: "back", x: 172, y: 522, location: "崑崙直上三寸，腓骨與跟腱之間。", action: "舒筋活絡、退熱散風。", indications: "頭痛、腰骶痛、下肢痿痺、外踝腫痛。", special: "陽蹺脈郄穴" },
  { id: "BL63", name: "金門", py: "Jīnmén", meridian: "足太陽膀胱經", view: "back", x: 168, y: 548, location: "外踝前緣直下，骰骨外側凹陷處。", action: "舒筋活絡、寧神開竅。", indications: "癲癇、小兒驚風、腰痛、下肢痿痺、外踝痛。", special: "膀胱經郄穴" },
  { id: "BL12", name: "風門", py: "Fēngmén", meridian: "足太陽膀胱經", view: "back", x: 185, y: 166, location: "第二胸椎棘突下，旁開1.5寸。", action: "宣肺解表、疏風清熱。", indications: "感冒、咳嗽、發熱、頭痛、項強、胸背痛。" },
  { id: "BL14", name: "厥陰俞", py: "Juéyīnshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 179, location: "第四胸椎棘突下，旁開1.5寸。", action: "寬胸理氣、寧心安神。", indications: "心痛、心悸、胸悶、咳嗽、嘔吐。", special: "心包之背俞穴" },
  { id: "BL16", name: "督俞", py: "Dūshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 193, location: "第六胸椎棘突下，旁開1.5寸。", action: "理氣寬胸、強心通陽。", indications: "心痛、胸悶、腹痛、呃逆、寒熱氣喘。" },
  { id: "BL22", name: "三焦俞", py: "Sānjiāoshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 250, location: "第一腰椎棘突下，旁開1.5寸。", action: "調理三焦、健脾利水。", indications: "腹脹、腸鳴、嘔吐、水腫、腰背強痛。", special: "三焦之背俞穴" },
  { id: "BL24", name: "氣海俞", py: "Qìhǎishù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 266, location: "第三腰椎棘突下，旁開1.5寸。", action: "益腎壯陽、調經止痛。", indications: "腰痛、痛經、痔漏、下肢痿痺。" },
  { id: "BL26", name: "關元俞", py: "Guānyuánshù", meridian: "足太陽膀胱經", view: "back", x: 186, y: 283, location: "第五腰椎棘突下，旁開1.5寸。", action: "培補元氣、調理下焦。", indications: "腰痛、泄瀉、小便不利、消渴。" },
  { id: "BL27", name: "小腸俞", py: "Xiǎochángshù", meridian: "足太陽膀胱經", view: "back", x: 188, y: 294, location: "第一骶椎旁開1.5寸，平第一骶後孔。", action: "通調二便、清熱利濕。", indications: "小腹脹痛、泄瀉、痢疾、遺尿、帶下。", special: "小腸之背俞穴" },
  { id: "BL28", name: "膀胱俞", py: "Pángguāngshù", meridian: "足太陽膀胱經", view: "back", x: 190, y: 303, location: "第二骶椎旁開1.5寸，平第二骶後孔。", action: "通調膀胱、清熱利濕。", indications: "小便不利、遺尿、泄瀉、便秘、腰骶痛。", special: "膀胱之背俞穴" },
  { id: "BL43", name: "膏肓", py: "Gāohuāng", meridian: "足太陽膀胱經", view: "back", x: 174, y: 180, location: "第四胸椎棘突下，旁開3寸。", action: "補虛益損、養肺安神。", indications: "久咳、虛勞、盜汗、健忘、肺癆（灸之為保健要穴）。" },
  { id: "BL52", name: "志室", py: "Zhìshì", meridian: "足太陽膀胱經", view: "back", x: 172, y: 258, location: "第二腰椎棘突下，旁開3寸。", action: "補腎益精、利濕通絡。", indications: "遺精、陽痿、小便不利、水腫、腰脊強痛。" },
  { id: "BL54", name: "秩邊", py: "Zhìbiān", meridian: "足太陽膀胱經", view: "back", x: 210, y: 308, location: "第四骶椎棘突下，旁開3寸。", action: "舒筋活絡、強腰健腿。", indications: "腰骶痛、坐骨神經痛、下肢痿痺、痔疾、小便不利。" },
  { id: "BL39", name: "委陽", py: "Wěiyáng", meridian: "足太陽膀胱經", view: "back", x: 192, y: 406, location: "膕橫紋外側端，股二頭肌腱內側緣。", action: "通利三焦、舒筋活絡。", indications: "小便不利、水腫、腰脊強痛、腿足攣痛。", special: "三焦之下合穴" },
  { id: "GV15", name: "啞門", py: "Yǎmén", meridian: "督脈", view: "back", x: 200, y: 120, location: "後髮際正中直上0.5寸，第一頸椎下。", action: "開竅醒神、清心利舌。", indications: "暴喑、舌強不語、癲狂、頭痛、項強。" },
  { id: "GV13", name: "陶道", py: "Táodào", meridian: "督脈", view: "back", x: 200, y: 160, location: "第一胸椎棘突下凹陷，後正中線上。", action: "解表清熱、寧神。", indications: "頭痛、項強、發熱、瘧疾、癲狂。" },
  { id: "GV10", name: "靈台", py: "Língtái", meridian: "督脈", view: "back", x: 200, y: 193, location: "第六胸椎棘突下凹陷，後正中線上。", action: "清熱解毒、宣肺止咳。", indications: "咳嗽、氣喘、疔瘡、項背強痛。" },
  { id: "GV8", name: "筋縮", py: "Jīnsuō", meridian: "督脈", view: "back", x: 200, y: 212, location: "第九胸椎棘突下凹陷，後正中線上。", action: "平肝熄風、寧神鎮痙。", indications: "癲癇、抽搐、脊背強急、胃痛。" },
  { id: "GV6", name: "脊中", py: "Jǐzhōng", meridian: "督脈", view: "back", x: 200, y: 228, location: "第十一胸椎棘突下凹陷，後正中線上。", action: "健脾利濕、寧神鎮痙。", indications: "腹瀉、黃疸、痔疾、癲癇、腰脊強痛。" },
  { id: "GV2", name: "腰俞", py: "Yāoshù", meridian: "督脈", view: "back", x: 200, y: 305, location: "骶管裂孔正中，後正中線上。", action: "調經清熱、強腰利濕。", indications: "月經不調、痔疾、腰脊強痛、下肢痿痺、癲癇。" },
  { id: "BL10", name: "天柱", py: "Tiānzhù", meridian: "足太陽膀胱經", view: "back", x: 190, y: 117, location: "後髮際正中旁開1.3寸，斜方肌外緣凹陷。", action: "祛風通絡、清頭明目。", indications: "頭痛、項強、肩背痛、鼻塞、目眩。" },
  { id: "GB12", name: "完骨", py: "Wángǔ", meridian: "足少陽膽經", view: "back", x: 214, y: 100, location: "耳後乳突後下方凹陷處。", action: "祛風清熱、寧神通絡。", indications: "頭痛、頸項強痛、失眠、面癱、齒痛。" },
  { id: "EX-HN16", name: "安眠", py: "Ānmián", meridian: "經外奇穴", view: "back", x: 210, y: 102, location: "翳風與風池連線中點。", action: "鎮靜安神、平肝潛陽。", indications: "失眠、頭痛、眩暈、心悸、煩躁。" },
  { id: "GV18", name: "強間", py: "Qiángjiān", meridian: "督脈", view: "back", x: 200, y: 88, location: "後髮際正中直上四寸（腦戶上1.5寸）。", action: "寧神鎮痙、平肝熄風。", indications: "頭痛、目眩、項強、癲狂、失眠。" },
  { id: "GV17", name: "腦戶", py: "Nǎohù", meridian: "督脈", view: "back", x: 200, y: 102, location: "枕外隆凸上緣凹陷，後髮際正中直上2.5寸。", action: "醒神開竅、平肝熄風。", indications: "頭痛、頭暈、項強、癲癇、失音。" },
  { id: "GV11", name: "神道", py: "Shéndào", meridian: "督脈", view: "back", x: 200, y: 186, location: "第五胸椎棘突下凹陷，後正中線上。", action: "寧心安神、清熱平喘。", indications: "心痛、心悸、失眠、健忘、咳嗽、脊背強痛。" },
  { id: "GV7", name: "中樞", py: "Zhōngshū", meridian: "督脈", view: "back", x: 200, y: 221, location: "第十胸椎棘突下凹陷，後正中線上。", action: "健脾利濕、清熱止痛。", indications: "黃疸、嘔吐、腹滿、腰背痛。" },
  { id: "GV5", name: "懸樞", py: "Xuánshū", meridian: "督脈", view: "back", x: 200, y: 250, location: "第一腰椎棘突下凹陷，後正中線上。", action: "助陽健脾、通調腸氣。", indications: "腹脹、泄瀉、腰脊強痛。" },
  { id: "BL42", name: "魄戶", py: "Pòhù", meridian: "足太陽膀胱經", view: "back", x: 174, y: 172, location: "第三胸椎棘突下，旁開3寸。", action: "宣肺平喘、舒筋活絡。", indications: "咳嗽、氣喘、肺癆、項強、肩背痛。" },
  { id: "BL44", name: "神堂", py: "Shéntáng", meridian: "足太陽膀胱經", view: "back", x: 174, y: 186, location: "第五胸椎棘突下，旁開3寸。", action: "寬胸理氣、寧心安神。", indications: "心痛、心悸、胸悶、咳嗽、脊背強痛。" },
  { id: "BL45", name: "譩譆", py: "Yìxǐ", meridian: "足太陽膀胱經", view: "back", x: 174, y: 193, location: "第六胸椎棘突下，旁開3寸。", action: "宣肺理氣、通絡止痛。", indications: "咳嗽、氣喘、瘧疾、熱病、肩背痛。" },
  { id: "BL46", name: "膈關", py: "Géguān", meridian: "足太陽膀胱經", view: "back", x: 174, y: 200, location: "第七胸椎棘突下，旁開3寸。", action: "寬胸利膈、和胃降逆。", indications: "嘔吐、噯氣、飲食不下、脊背強痛。" },
  { id: "BL47", name: "魂門", py: "Húnmén", meridian: "足太陽膀胱經", view: "back", x: 173, y: 212, location: "第九胸椎棘突下，旁開3寸。", action: "疏肝理氣、健脾和胃。", indications: "胸脅脹痛、嘔吐、泄瀉、背痛。" },
  { id: "BL49", name: "意舍", py: "Yìshè", meridian: "足太陽膀胱經", view: "back", x: 173, y: 228, location: "第十一胸椎棘突下，旁開3寸。", action: "健脾和胃、利膽化濕。", indications: "腹脹、泄瀉、嘔吐、黃疸、納呆。" },
  { id: "BL50", name: "胃倉", py: "Wèicāng", meridian: "足太陽膀胱經", view: "back", x: 173, y: 242, location: "第十二胸椎棘突下，旁開3寸。", action: "和胃健脾、消食導滯。", indications: "胃脘痛、腹脹、小兒食積、背脊痛。" },
  { id: "BL51", name: "肓門", py: "Huāngmén", meridian: "足太陽膀胱經", view: "back", x: 172, y: 250, location: "第一腰椎棘突下，旁開3寸。", action: "理氣和胃、清熱消腫。", indications: "腹痛、痞塊、便秘、乳疾。" },
  { id: "BL53", name: "胞肓", py: "Bāohuāng", meridian: "足太陽膀胱經", view: "back", x: 196, y: 303, location: "第二骶椎旁開3寸，平第二骶後孔。", action: "補腎強腰、通利二便。", indications: "腰脊痛、腹脹、腸鳴、小便不利、便秘。" },
  { id: "BL7", name: "通天", py: "Tōngtiān", meridian: "足太陽膀胱經", view: "back", x: 193, y: 22, location: "前髮際正中直上4寸，旁開1.5寸。", action: "宣肺利鼻、清頭散風。", indications: "頭痛、眩暈、鼻塞、鼻淵、鼻衄。" },
  { id: "BL8", name: "絡卻", py: "Luòquè", meridian: "足太陽膀胱經", view: "back", x: 193, y: 40, location: "前髮際正中直上5.5寸，旁開1.5寸。", action: "清頭明目、安神。", indications: "頭暈、目視不明、耳鳴、癲狂。" },
  { id: "BL9", name: "玉枕", py: "Yùzhěn", meridian: "足太陽膀胱經", view: "back", x: 192, y: 98, location: "枕外隆凸上緣外側，後髮際正中旁開1.3寸。", action: "清頭明目、通竅。", indications: "頭項痛、目痛、鼻塞。" },
];

export const SYMPTOM_GROUPS: SymptomGroup[] = [
  { id: "common-cold", name: "感冒", category: "外感類", description: "外感風寒或風熱所致，可見惡寒或發熱、頭痛、鼻塞、咳嗽等，依表現不同選方。",
    formulas: [
      { name: "桂枝湯", pattern: "發熱、惡風、自汗出、脈浮緩 — 太陽中風表虛證", composition: "桂枝、芍藥、生薑、大棗、炙甘草", usage: "水煎溫服，服後可飲熱粥助微汗，每日一劑。", notes: "表實無汗、高熱者不宜；服藥期間忌生冷油膩。" },
      { name: "葛根湯", pattern: "惡寒、項背強痛、無汗、脈浮緊 — 表證兼項背拘急", composition: "葛根、麻黃、桂枝、芍藥、生薑、大棗、炙甘草", usage: "水煎溫服，每日一劑，分二次服，得汗為度。", notes: "體虛多汗、高血壓患者慎用。" },
      { name: "麻黃湯", pattern: "惡寒重、發熱、無汗、頭痛身痛、脈浮緊 — 太陽傷寒表實證", composition: "麻黃、桂枝、杏仁、炙甘草", usage: "水煎溫服，得汗即止，不可過量發汗。", notes: "體虛、自汗、心臟病及孕婦忌用。" },
      { name: "銀翹散", pattern: "發熱重、咽喉腫痛、口乾、舌紅 — 風熱表證", composition: "金銀花、連翹、薄荷、牛蒡子、桔梗、淡竹葉、荊芥、甘草", usage: "水煎或沖泡代茶飲，每日一至二劑。", notes: "風寒無汗惡寒者不宜，脾胃虛寒慎用。" },
    ], points: ["GV14", "LI4", "GV20"] },

  { id: "cough", name: "咳嗽", category: "肺系類", description: "依痰之寒熱與多寡區分證型，咳嗽久暫、痰色痰量是辨證關鍵。",
    formulas: [
      { name: "杏蘇散", pattern: "咳嗽痰白、惡寒、鼻塞流清涕 — 風寒咳嗽", composition: "杏仁、紫蘇葉、半夏、茯苓、陳皮、前胡、桔梗、枳殼、生薑、甘草", usage: "水煎溫服，每日一劑。", notes: "陰虛燥咳、咳血者不宜。" },
      { name: "桑菊飲", pattern: "咳嗽痰少、咽乾、發熱、舌紅 — 風熱咳嗽", composition: "桑葉、菊花、杏仁、連翹、薄荷、桔梗、甘草、蘆根", usage: "水煎服，每日一至二劑。", notes: "風寒咳嗽（怕冷痰白）不宜。" },
      { name: "二陳湯", pattern: "咳嗽痰多色白、胸悶、喉中痰鳴 — 痰濕咳嗽", composition: "半夏、陳皮、茯苓、炙甘草、生薑", usage: "水煎溫服，每日一劑，分二次飯後服。", notes: "燥咳、陰虛火旺者不宜。" },
    ], points: ["CV17", "LU1", "LU7"] },

  { id: "insomnia", name: "失眠", category: "神志類", description: "失眠常與心、肝、脾相關，依伴隨症狀（陰虛火旺、肝血不足、心脾兩虛）選方。",
    formulas: [
      { name: "天王補心丹", pattern: "心悸、健忘、口乾、舌紅 — 陰虛火旺型失眠", composition: "生地、麥冬、天冬、酸棗仁、柏子仁、當歸、丹參、人參、五味子、遠志、茯苓、桔梗", usage: "蜜丸或科學中藥，每日二至三次，睡前服用。", notes: "脾胃虛寒、易腹瀉者慎用。" },
      { name: "酸棗仁湯", pattern: "虛煩不眠、心悸、易驚 — 肝血不足型失眠", composition: "酸棗仁、茯苓、知母、川芎、炙甘草", usage: "水煎服，睡前一至二小時溫服。", notes: "外感發熱期間不宜服用。" },
      { name: "歸脾湯", pattern: "失眠多夢、健忘、食慾不振、倦怠乏力 — 心脾兩虛", composition: "白朮、茯苓、黃耆、龍眼肉、酸棗仁、人參、木香、當歸、遠志、炙甘草、生薑、大棗", usage: "水煎溫服，每日一劑，分二次服。", notes: "實熱證、舌苔黃厚者不宜。" },
    ], points: ["HT7", "PC6", "GV20", "SP6"] },

  { id: "anxiety", name: "情緒煩躁／焦慮", category: "神志類", description: "情緒鬱結與肝氣不暢相關，輕者藥性平和方劑即可，較重者須疏肝理氣。",
    formulas: [
      { name: "甘麥大棗湯", pattern: "心神不寧、易哭、胸悶嘆氣 — 臟躁輕證", composition: "甘草、淮小麥、大棗", usage: "水煎代茶飲，每日一劑。", notes: "藥性平和，但症狀持續應就醫評估。" },
      { name: "逍遙散", pattern: "胸脅脹悶、易怒、經前症狀加重、嘆氣 — 肝鬱證", composition: "柴胡、白芍、當歸、白朮、茯苓、炙甘草、生薑、薄荷", usage: "水煎溫服或科學中藥沖服，每日一至二次。", notes: "陰虛血燥、潮熱明顯者慎用。" },
    ], points: ["LR3", "PC6", "GV20"] },

  { id: "indigestion", name: "胃脹消化不良", category: "脾胃類", description: "依虛實區分：脾胃氣虛者宜補益，食積氣滯者宜消導。",
    formulas: [
      { name: "香砂六君子湯", pattern: "食後腹脹、食慾不振、倦怠、大便稀軟 — 脾胃氣虛", composition: "黨參、白朮、茯苓、甘草、陳皮、半夏、木香、砂仁", usage: "水煎溫服，每日一劑，分二次飯前服。", notes: "實熱證（口臭、便秘、舌苔黃厚）不宜單用。" },
      { name: "保和丸", pattern: "噯腐吞酸、腹脹拒按、大便臭穢 — 食積證", composition: "山楂、神麴、半夏、茯苓、陳皮、連翹、萊菔子", usage: "成藥每次一份，每日二至三次，飯後服用。", notes: "脾胃虛弱無食積者不宜長期服用。" },
    ], points: ["ST36", "CV12"] },

  { id: "constipation", name: "便秘", category: "脾胃類", description: "腸燥便秘多見口乾、便硬；氣虛便秘多見年長體弱、便質不硬但排出無力。",
    formulas: [
      { name: "麻子仁丸", pattern: "大便乾結、數日一行、腹部脹滿、口乾 — 腸燥便秘", composition: "火麻仁、杏仁、芍藥、枳實、厚朴、大黃", usage: "成藥每次一至二丸，每日一至二次。", notes: "含大黃，孕婦、久瀉者忌用，不宜長期連續服用。" },
      { name: "補中益氣湯", pattern: "排便無力、便質不硬但難排出、神疲乏力 — 氣虛便秘", composition: "黃耆、人參、白朮、當歸、陳皮、升麻、柴胡、炙甘草、生薑、大棗", usage: "水煎溫服，每日一劑。", notes: "實熱便秘、舌紅苔黃者不宜。" },
    ], points: ["ST36", "CV12"] },

  { id: "dysmenorrhea", name: "月經不調／痛經", category: "婦科類", description: "依經色、經量與腹痛性質區分寒凝、血虛、血瘀等證型。",
    formulas: [
      { name: "溫經湯", pattern: "經色暗、量少、小腹冷痛、畏寒 — 寒凝胞宮", composition: "吳茱萸、當歸、川芎、芍藥、人參、桂枝、阿膠、牡丹皮、生薑、甘草、半夏、麥冬", usage: "經前一週開始水煎溫服，每日一劑。", notes: "經量過多、懷孕者禁用。" },
      { name: "四物湯", pattern: "經量少、色淡、頭暈乏力、面色蒼白 — 血虛證", composition: "當歸、川芎、芍藥、熟地黃", usage: "水煎溫服，月經結束後連服數日。", notes: "血瘀有塊、舌暗者宜配合活血藥。" },
      { name: "桃紅四物湯", pattern: "經色暗紫有血塊、小腹刺痛、舌暗 — 血瘀證", composition: "桃仁、紅花、當歸、川芎、芍藥、熟地黃", usage: "水煎溫服，經前數日開始服用。", notes: "經量過多、孕婦禁用。" },
    ], points: ["SP6", "CV4", "SP10"] },

  { id: "headache", name: "頭痛", category: "肝腎類", description: "外感誘發的頭痛與肝陽上亢型頭痛在誘因與伴隨症狀上不同，選方亦異。",
    formulas: [
      { name: "川芎茶調散", pattern: "頭痛因感冒誘發、鼻塞、惡風 — 外感頭痛", composition: "川芎、白芷、羌活、荊芥、防風、薄荷、細辛、甘草", usage: "以淡茶水沖服，頭痛發作時服用。", notes: "血虛、陰虛火旺型頭痛不宜，孕婦慎用。" },
      { name: "天麻鉤藤飲", pattern: "頭痛眩暈、急躁易怒、失眠、面紅 — 肝陽上亢", composition: "天麻、鉤藤、石決明、黃芩、山梔子、牛膝、杜仲、益母草、桑寄生、夜交藤、茯神", usage: "水煎溫服，每日一劑。", notes: "氣血兩虛、面色蒼白者不宜單用。" },
    ], points: ["GV20", "LI4", "LR3"] },

  { id: "lower-back-knee", name: "腰膝痠軟／疲勞", category: "肝腎類", description: "腎陰虛多兼潮熱口乾；腎陽虛多兼畏寒夜尿，兩者用方寒熱迥異。",
    formulas: [
      { name: "六味地黃丸", pattern: "腰膝痠軟、口乾、潮熱、夜尿多 — 腎陰虛", composition: "熟地黃、山藥、山茱萸、澤瀉、茯苓、牡丹皮", usage: "成藥每次一份，每日二至三次，溫水送服。", notes: "舌苔厚膩、腹瀉、感冒發熱期間不宜。" },
      { name: "金匱腎氣丸", pattern: "腰膝冷痛、畏寒、夜尿頻多、四肢不溫 — 腎陽虛", composition: "熟地黃、山藥、山茱萸、澤瀉、茯苓、牡丹皮、桂枝、附子", usage: "成藥每次一份，每日二至三次，溫水送服。", notes: "含附子，陰虛火旺、孕婦不宜，須遵醫囑。" },
    ], points: ["KI3", "ST36", "CV4", "GV4"] },

  { id: "edema", name: "水腫", category: "脾胃類", description: "水濕內停與氣虛水腫的差別在於是否伴隨自汗、怕風與身體沉重感。",
    formulas: [
      { name: "五苓散", pattern: "下肢浮腫、小便量少、口渴但不欲多飲 — 水濕內停", composition: "豬苓、茯苓、澤瀉、白朮、桂枝", usage: "沖服或水煎服，每日一至二劑，多飲溫水。", notes: "陰虛口乾、嚴重腎臟疾病須醫師評估。" },
      { name: "防己黃耆湯", pattern: "下肢浮腫、汗出怕風、身體沉重 — 氣虛水腫", composition: "防己、黃耆、白朮、甘草、生薑、大棗", usage: "水煎溫服，每日一劑。", notes: "表實無汗、高血壓控制不佳者慎用。" },
    ], points: ["SP6", "SP9", "ST36"] },
];
